# SPDX-FileCopyrightText: {% now 'utc', '%Y' %} {{ cookiecutter.author_name }}
# SPDX-License-Identifier: {{ cookiecutter.license }}

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: ["tekktrik"]
    versioning-strategy: increase
